### ISSUE TITLE
Device error

### ISSUE THREAD

**Issue by evilmarty** [evilmarty/eufy-security-mqtt#1]
```
/app/node_modules/eufy-security-client/build/http/device.js:267
        throw new error_1.InvalidPropertyError(`Property ${name} invalid`);
              ^
InvalidPropertyError: Property personName invalid
    at Camera.getPropertyMetadata (/app/node_modules/eufy-security-client/build/http/device.js:267:15)
    at Gateway.updateComponent (/app/src/index.js:255:29)
    at EufySecurity.<anonymous> (/app/src/index.js:96:12)
    at EufySecurity.emit (node:events:394:28)
    at EufySecurity.onDevicePropertyChanged (/app/node_modules/eufy-security-client/build/eufysecurity.js:1031:18)
    at Camera.<anonymous> (/app/node_modules/eufy-security-client/build/eufysecurity.js:383:81)
    at Camera.emit (node:events:394:28)
    at Camera.updateProperty (/app/node_modules/eufy-security-client/build/http/device.js:80:26)
    at Camera.processPushNotification (/app/node_modules/eufy-security-client/build/http/device.js:809:30)
    at /app/node_modules/eufy-security-client/build/eufysecurity.js:684:28
```

**Comment by evilmarty** [comment]
I believe this has been fixed.
