### ISSUE TITLE
Always got error message at start "Arguments requis manquants : username, password"

### ISSUE THREAD

**Issue by BabaIsYou** [evilmarty/eufy-security-mqtt#17]
Installing eufy-security-mqtt and eufy-security-client as described but whatever syntax I used to start I got an error telling that username and password arguments are missing : 
![image](https://user-images.githubusercontent.com/85300265/176521070-66520ccb-5627-4dd1-afa1-b2f746be6403.png)
![image](https://user-images.githubusercontent.com/85300265/176521184-27a408bf-c499-46ad-be5b-bac1a566f23d.png)

I tried with or without quotes, it didn't change the error message. What do I have to check ?

**Comment by evilmarty** [comment]
It's hard to know for sure. You can try run the command with '--debug' to see more info. I suspect you may need to supply user and password for MQTT though.

**Comment by BabaIsYou** [comment]
Thanks for quick feedback.
The weird part is that whatever parameter I put in my command, I got the same error message, nothing more. Even with --debug
My mosquitto instance is running fine with default parameters and no username or password.

For information I'm on a Raspberry Pi
`$ uname -a
Linux domoticz 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

$ node --version
v16.15.1

$ npm -v
8.13.1

$ npm run
Lifecycle scripts included in eufy-security-mqtt@0.4.1:
  start
    node src/cli.js

available via `npm run-script`:
  help
    node src/cli.js --help

$ systemctl status mosquitto

> ● mosquitto.service - Mosquitto MQTT v3.1/v3.1.1 Broker
>    Loaded: loaded (/lib/systemd/system/mosquitto.service; enabled; vendor preset
>    Active: active (running) since Wed 2022-06-15 18:26:03 EDT; 2 weeks 0 days ag
>      Docs: man:mosquitto.conf(5)
>            man:mosquitto(8)
>  Main PID: 1444 (mosquitto)
>     Tasks: 1 (limit: 3860)
>    CGroup: /system.slice/mosquitto.service
>            └─1444 /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
> 
> jun 15 18:26:02 domoticz systemd[1]: Starting Mosquitto MQTT v3.1/v3.1.1 Broker.
> jun 15 18:26:03 domoticz systemd[1]: Started Mosquitto MQTT v3.1/v3.1.1 Broker.
> 

$ cat /etc/mosquitto/mosquitto.conf

> # Place your local configuration in /etc/mosquitto/conf.d/
> #
> # A full description of the configuration file is at
> # /usr/share/doc/mosquitto/examples/mosquitto.conf.example
> 
> pid_file /var/run/mosquitto.pid
> 
> persistence true
> persistence_location /var/lib/mosquitto/
> 
> log_dest file /tmp/log/mosquitto.log
> 
> include_dir /etc/mosquitto/conf.d

`

**Comment by evilmarty** [comment]
I don't suspect it's an issue with your mosquito server. Can you try supply a username and password for MQTT? Alternatively, you can create a JSON config file and pass that as `--config config.json`.

```json
{
  "username": "...",
  "password": "...",
  "mqtt": {
    "host": "...",
    "username": "...",
    "password": "..."
  }
}
```

**Comment by BabaIsYou** [comment]
Hi,

Exactly the same error, seems like parameters are not parsed !?
I also added 
listener 1883
allow_anonymous true

in my /etc/mosquitto/mosquitto.conf to be sure and even when using mosquitto_pub or mosquitto_sub I never add an username or password.

Just to mention that I install node and npm following this tuto https://www.makersupplies.sg/blogs/tutorials/how-to-install-node-js-and-npm-on-the-raspberry-pi because standard package on raspbian buster are too old to have your library to be used.

**Comment by BabaIsYou** [comment]
Trying to launch it usinf g only node in place of npm and got this
`pi@domoticz:~/eufy-security-mqtt $ node src/cli.js --username XXXXXXXXXX --password XXXXXXXXXXXX --debug
info: Connected to MQTT broker: mqtt://localhost:1883
info: Connecting to Eufy Security...
/home/pi/eufy-security-mqtt/node_modules/eufy-security-client/build/eufysecurity.js:547
        await this.api.login(options)
                       ^

TypeError: Cannot read properties of undefined (reading 'login')
    at EufySecurity.connect (/home/pi/eufy-security-mqtt/node_modules/eufy-security-client/build/eufysecurity.js:547:24)
    at default.connect (file:///home/pi/eufy-security-mqtt/src/index.js:225:45)
    at MqttClient.<anonymous> (file:///home/pi/eufy-security-mqtt/src/index.js:165:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`
The I guess that connection to MQTT is not the issue.

With --debug I got log file but nothing I can understand

> 0 verbose cli /usr/local/bin/node /usr/local/bin/npm
> 1 info using npm@8.13.1
> 2 info using node@v16.15.1
> 3 timing npm:load:whichnode Completed in 0ms
> 4 timing config:load:defaults Completed in 5ms
> 5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
> 6 timing config:load:builtin Completed in 3ms
> 7 timing config:load:cli Completed in 7ms
> 8 timing config:load:env Completed in 1ms
> 9 timing config:load:file:/home/pi/eufy-security-mqtt/.npmrc Completed in 0ms
> 10 timing config:load:project Completed in 8ms
> 11 timing config:load:file:/home/pi/.npmrc Completed in 1ms
> 12 timing config:load:user Completed in 1ms
> 13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
> 14 timing config:load:global Completed in 0ms
> 15 timing config:load:validate Completed in 0ms
> 16 timing config:load:credentials Completed in 3ms
> 17 timing config:load:setEnvs Completed in 3ms
> 18 timing config:load Completed in 34ms
> 19 timing npm:load:configload Completed in 34ms
> 20 timing npm:load:mkdirpcache Completed in 3ms
> 21 timing npm:load:mkdirplogs Completed in 1ms
> 22 verbose title npm run start XXXXXXXX YYYYYYYY
> 23 verbose argv "run" "start" "--username" "XXXXXXXX" "--password" "YYYYYYY" "--debug"
> 24 timing npm:load:setTitle Completed in 4ms
> 25 timing config:load:flatten Completed in 10ms
> 26 timing npm:load:display Completed in 16ms
> 27 verbose logfile logs-max:10 dir:/home/pi/.npm/_logs
> 28 verbose logfile /home/pi/.npm/_logs/2022-07-05T19_42_24_644Z-debug-0.log
> 29 timing npm:load:logFile Completed in 15ms
> 30 timing npm:load:timers Completed in 0ms
> 31 timing npm:load:configScope Completed in 0ms
> 32 timing npm:load Completed in 78ms
> 33 silly logfile start cleaning logs, removing 1 files
> 34 silly logfile done cleaning log files
> 35 timing command:run Completed in 1988ms
> 36 verbose exit 1
> 37 timing npm Completed in 2093ms
> 38 verbose code 1
